In [1]:
import pandas as pd

df = pd.read_csv("../data/processed_data01.csv")

df.head()

,customer_id,age,annual_income,months_active,avg_monthly_spend,purchase_frequency,avg_order_value,discount_usage_rate,return_rate,browsing_time_minutes,support_interactions,payment_method,region,customer_segment
0,33554,53,100473.211709,63,121.430565,0.817268,66.820403,0.117256,0.023144,77.298393,2.0,Card,Semi-Urban,Occasional
1,9428,54,54730.644845,67,572.552674,3.176551,137.087449,0.261647,0.429054,92.132565,2.0,Wallet,Urban,Occasional
2,200,44,58268.121079,57,266.593896,2.713168,71.796888,0.284785,0.011854,155.194768,1.0,UPI,Rural,Occasional
3,12448,54,64829.795654,40,691.452358,5.553977,105.501185,0.104832,0.399686,113.917756,0.0,Wallet,Rural,High_Value
4,39490,28,27431.467873,15,832.664792,1.348389,354.568534,0.409204,0.039517,50.123656,1.0,Card,Semi-Urban,Occasional

In [2]:
df.duplicated().sum()

np.int64(0)

In [3]:
df['customer_id'].duplicated().sum()

np.int64(0)

In [4]:
df = df.drop_duplicates(subset='customer_id')

In [5]:
numeric_columns = [
    'age',
    'annual_income',
    'avg_monthly_spend',
    'purchase_frequency',
    'discount_usage_rate',
    'return_rate',
    'browsing_time_minutes',
    'support_interactions'
]

In [6]:
for col in numeric_columns:
    df[col] = df[col].fillna(df[col].mean())

In [7]:
df.isnull().sum()

customer_id              0
age                      0
annual_income            0
months_active            0
avg_monthly_spend        0
purchase_frequency       0
avg_order_value          0
discount_usage_rate      0
return_rate              0
browsing_time_minutes    0
support_interactions     0
payment_method           0
region                   0
customer_segment         0
dtype: int64

In [8]:
df['age'].describe()

count    50000.000000
mean        44.002820
std         15.269871
min         18.000000
25%         31.000000
50%         44.000000
75%         57.000000
max         70.000000
Name: age, dtype: float64

In [9]:
df[df['age']<0]

Empty DataFrame
Columns: [customer_id, age, annual_income, months_active, avg_monthly_spend, purchase_frequency, avg_order_value, discount_usage_rate, return_rate, browsing_time_minutes, support_interactions, payment_method, region, customer_segment]
Index: []

In [10]:
df['annual_income'].describe()

count     50000.000000
mean      44542.620904
std       29583.985243
min        2946.317892
25%       25112.704208
50%       38710.586730
75%       53830.215138
max      530788.317921
Name: annual_income, dtype: float64

In [11]:
df[df['annual_income'] < 0]

Empty DataFrame
Columns: [customer_id, age, annual_income, months_active, avg_monthly_spend, purchase_frequency, avg_order_value, discount_usage_rate, return_rate, browsing_time_minutes, support_interactions, payment_method, region, customer_segment]
Index: []

In [12]:
df['avg_monthly_spend'].describe()

count    50000.000000
mean       337.294238
std        199.403722
min          8.072298
25%        197.220824
50%        309.826593
75%        429.191654
max       3026.342238
Name: avg_monthly_spend, dtype: float64

In [13]:
df[df['avg_monthly_spend'] < 0]

Empty DataFrame
Columns: [customer_id, age, annual_income, months_active, avg_monthly_spend, purchase_frequency, avg_order_value, discount_usage_rate, return_rate, browsing_time_minutes, support_interactions, payment_method, region, customer_segment]
Index: []

In [14]:
df['return_rate'].describe()

count    50000.000000
mean         0.148964
std          0.107725
min          0.000050
25%          0.066834
50%          0.130674
75%          0.203893
max          0.830395
Name: return_rate, dtype: float64

In [15]:
df[df['return_rate'] < 0]

Empty DataFrame
Columns: [customer_id, age, annual_income, months_active, avg_monthly_spend, purchase_frequency, avg_order_value, discount_usage_rate, return_rate, browsing_time_minutes, support_interactions, payment_method, region, customer_segment]
Index: []

In [16]:
df['discount_usage_rate'].describe()

count    50000.000000
mean         0.284358
std          0.155124
min          0.000534
25%          0.166100
50%          0.273935
75%          0.380198
max          0.934655
Name: discount_usage_rate, dtype: float64

In [17]:
df.to_csv("../data/cleaned_data02.csv", index=False)

In [18]:
import pickle

with open("../data/processed_variables.pkl", "wb") as f:
    pickle.dump({
        "df": df,
        "numeric_columns": numeric_columns
    }, f)