CREATE BUSINESS FEATURES

In [1]:
import pandas as pd
df = pd.read_csv('../data/analysed_data03.csv')
df.head()

,customer_id,age,annual_income,months_active,avg_monthly_spend,purchase_frequency,avg_order_value,discount_usage_rate,return_rate,browsing_time_minutes,support_interactions,payment_method,region,customer_segment
0,33554,53,100473.211709,63,121.430565,0.817268,66.820403,0.117256,0.023144,77.298393,2.0,Card,Semi-Urban,Occasional
1,9428,54,54730.644845,67,572.552674,3.176551,137.087449,0.261647,0.429054,92.132565,2.0,Wallet,Urban,Occasional
2,200,44,58268.121079,57,266.593896,2.713168,71.796888,0.284785,0.011854,155.194768,1.0,UPI,Rural,Occasional
3,12448,54,64829.795654,40,691.452358,5.553977,105.501185,0.104832,0.399686,113.917756,0.0,Wallet,Rural,High_Value
4,39490,28,27431.467873,15,832.664792,1.348389,354.568534,0.409204,0.039517,50.123656,1.0,Card,Semi-Urban,Occasional

In [2]:
# Estimated Annual Spending
df['estimated_annual_spend']=(df['avg_monthly_spend']*12)

In [3]:
df['purchase_value_index']=(
    df['purchase_frequency']*df['avg_order_value']
)

In [4]:
df['engagement_score']=(
    df['browsing_time_minutes']*
    df['purchase_frequency']
)

In [5]:
df['discount_dependency'] = df['discount_usage_rate']

In [6]:
df['customer_value_score'] = (
    df['avg_monthly_spend']*             df['purchase_frequency']
)

In [7]:
df.head()

,customer_id,age,annual_income,months_active,avg_monthly_spend,purchase_frequency,avg_order_value,discount_usage_rate,return_rate,browsing_time_minutes,support_interactions,payment_method,region,customer_segment,estimated_annual_spend,purchase_value_index,engagement_score,discount_dependency,customer_value_score
0,33554,53,100473.211709,63,121.430565,0.817268,66.820403,0.117256,0.023144,77.298393,2.0,Card,Semi-Urban,Occasional,1457.166781,54.610162,63.173486,0.117256,99.241287
1,9428,54,54730.644845,67,572.552674,3.176551,137.087449,0.261647,0.429054,92.132565,2.0,Wallet,Urban,Occasional,6870.632088,435.465225,292.663757,0.261647,1818.742563
2,200,44,58268.121079,57,266.593896,2.713168,71.796888,0.284785,0.011854,155.194768,1.0,UPI,Rural,Occasional,3199.126755,194.797008,421.069457,0.284785,723.313990
3,12448,54,64829.795654,40,691.452358,5.553977,105.501185,0.104832,0.399686,113.917756,0.0,Wallet,Rural,High_Value,8297.428299,585.951173,632.696615,0.104832,3840.310600
4,39490,28,27431.467873,15,832.664792,1.348389,354.568534,0.409204,0.039517,50.123656,1.0,Card,Semi-Urban,Occasional,9991.977507,478.096258,67.586178,0.409204,1122.755920

SELECT FEATURES FOR CLUSTERING

In [8]:
features = [
    'age','annual_income','months_active','avg_monthly_spend','purchase_frequency','avg_order_value','discount_usage_rate','return_rate','browsing_time_minutes','support_interactions'
]

In [9]:
categorical_columns = ['payment_method','region']

In [10]:
df_encoded = pd.get_dummies(
    df,
    columns=['payment_method','region'],
    drop_first=True
)

In [11]:
df_encoded.head()

,customer_id,age,annual_income,months_active,avg_monthly_spend,purchase_frequency,avg_order_value,discount_usage_rate,return_rate,browsing_time_minutes,...,customer_segment,estimated_annual_spend,purchase_value_index,engagement_score,discount_dependency,customer_value_score,payment_method_UPI,payment_method_Wallet,region_Semi-Urban,region_Urban
0,33554,53,100473.211709,63,121.430565,0.817268,66.820403,0.117256,0.023144,77.298393,...,Occasional,1457.166781,54.610162,63.173486,0.117256,99.241287,False,False,True,False
1,9428,54,54730.644845,67,572.552674,3.176551,137.087449,0.261647,0.429054,92.132565,...,Occasional,6870.632088,435.465225,292.663757,0.261647,1818.742563,False,True,False,True
2,200,44,58268.121079,57,266.593896,2.713168,71.796888,0.284785,0.011854,155.194768,...,Occasional,3199.126755,194.797008,421.069457,0.284785,723.313990,True,False,False,False
3,12448,54,64829.795654,40,691.452358,5.553977,105.501185,0.104832,0.399686,113.917756,...,High_Value,8297.428299,585.951173,632.696615,0.104832,3840.310600,False,True,False,False
4,39490,28,27431.467873,15,832.664792,1.348389,354.568534,0.409204,0.039517,50.123656,...,Occasional,9991.977507,478.096258,67.586178,0.409204,1122.755920,False,False,True,False

final ml set

In [12]:
features = [
    "age",
    "annual_income",
    "months_active",
    "avg_monthly_spend",
    "purchase_frequency",
    "avg_order_value",
    "discount_usage_rate",
    "return_rate",
    "browsing_time_minutes",
    "support_interactions",
    "payment_method_UPI",
    "payment_method_Wallet",
    "region_Semi-Urban",
    "region_Urban"
]

In [13]:
df_encoded.columns

Index(['customer_id', 'age', 'annual_income', 'months_active',
       'avg_monthly_spend', 'purchase_frequency', 'avg_order_value',
       'discount_usage_rate', 'return_rate', 'browsing_time_minutes',
       'support_interactions', 'customer_segment', 'estimated_annual_spend',
       'purchase_value_index', 'engagement_score', 'discount_dependency',
       'customer_value_score', 'payment_method_UPI', 'payment_method_Wallet',
       'region_Semi-Urban', 'region_Urban'],
      dtype='str')

In [14]:
x = df_encoded[features]

In [15]:
# x = x.astype(int)

In [16]:
x.head()

,age,annual_income,months_active,avg_monthly_spend,purchase_frequency,avg_order_value,discount_usage_rate,return_rate,browsing_time_minutes,support_interactions,payment_method_UPI,payment_method_Wallet,region_Semi-Urban,region_Urban
0,53,100473.211709,63,121.430565,0.817268,66.820403,0.117256,0.023144,77.298393,2.0,False,False,True,False
1,54,54730.644845,67,572.552674,3.176551,137.087449,0.261647,0.429054,92.132565,2.0,False,True,False,True
2,44,58268.121079,57,266.593896,2.713168,71.796888,0.284785,0.011854,155.194768,1.0,True,False,False,False
3,54,64829.795654,40,691.452358,5.553977,105.501185,0.104832,0.399686,113.917756,0.0,False,True,False,False
4,28,27431.467873,15,832.664792,1.348389,354.568534,0.409204,0.039517,50.123656,1.0,False,False,True,False

In [17]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_scaled = scaler.fit_transform(x)

print(x_scaled.shape)
print(x.shape)

(50000, 14)
(50000, 14)

In [18]:
x_scaled_df = pd.DataFrame(
    x_scaled,
    columns=x.columns
    )

In [19]:
df.to_csv('../data/FinalFeatureDataset04.csv',index=False)

In [20]:
import pickle

with open("../data/processed_variables.pkl", "wb") as f:
    pickle.dump({
        "df": df,
        "features": features,
        "categorical_columns":categorical_columns,
        "df_encoded":df_encoded,
        "x":x,
        "x_scaled":x_scaled,
        "x_scaled_df":x_scaled_df,
        "scaler":scaler

    }, f)