In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/db_scaned_data06.csv")


df.head()

,age,annual_income,months_active,avg_monthly_spend,purchase_frequency,avg_order_value,discount_usage_rate,return_rate,browsing_time_minutes,support_interactions,payment_method_UPI,payment_method_Wallet,region_Semi-Urban,region_Urban,cluster,Cluster,KCluster
0,0.589217,1.890599,1.275919,-1.082267,-1.309297,-0.154198,0.0,0.0,0.392918,0.437317,-0.651475,-0.504652,1.512243,-0.991437,2,0,0
1,0.654706,0.344375,1.468347,1.179515,-0.415782,0.852451,0.0,0.0,0.767291,0.437317,-0.651475,1.981563,-0.661269,1.008637,0,1,1
2,-0.000185,0.463968,0.987277,-0.355086,-0.713621,-0.083307,0.0,0.0,2.339658,-0.395573,1.534977,-0.504652,-0.661269,-0.991437,3,0,0
3,0.654706,0.685746,0.169458,1.776304,0.179894,0.398750,0.0,0.0,1.291413,-1.228463,-0.651475,1.981563,-0.661269,-0.991437,0,1,1
4,-1.048010,-0.578397,-1.033217,2.483424,-1.011459,3.929109,0.0,0.0,-0.280954,-0.395573,-0.651475,-0.504652,1.512243,-0.991437,1,1,1

In [2]:
import pickle

with open("../data/processed_variables.pkl", "rb") as f:
    data = pickle.load(f)

df = data["df"]
features = data["features"]
x_scaled = data["x_scaled"]
x_scaled_df = data["x_scaled_df"]
scaler = data["scaler"]
final_kmeans = ["final_kmeans"]
dbscan_results =["dbscan_results"]

c:\Users\manya\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:525: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.9.1 when using version 1.9.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [3]:
from sklearn.cluster import AgglomerativeClustering

hierarchical = AgglomerativeClustering(
    n_clusters=4
)

hierarchical_labels = hierarchical.fit_predict(x_scaled)

df["Hierarchical_Cluster"] = hierarchical_labels

In [4]:
df.head()

,customer_id,age,annual_income,months_active,avg_monthly_spend,purchase_frequency,avg_order_value,discount_usage_rate,return_rate,browsing_time_minutes,...,region,customer_segment,estimated_annual_spend,purchase_value_index,engagement_score,discount_dependency,customer_value_score,Cluster,DBSCAN_Cluster,Hierarchical_Cluster
0,33554,53,100473.211709,63,121.430565,0.817268,66.820403,0.117256,0.023144,77.298393,...,Semi-Urban,Occasional,1457.166781,54.610162,63.173486,0.117256,99.241287,1,-1,1
1,9428,54,54730.644845,67,572.552674,3.176551,137.087449,0.261647,0.429054,92.132565,...,Urban,Occasional,6870.632088,435.465225,292.663757,0.261647,1818.742563,3,-1,2
2,200,44,58268.121079,57,266.593896,2.713168,71.796888,0.284785,0.011854,155.194768,...,Rural,Occasional,3199.126755,194.797008,421.069457,0.284785,723.313990,0,-1,3
3,12448,54,64829.795654,40,691.452358,5.553977,105.501185,0.104832,0.399686,113.917756,...,Rural,High_Value,8297.428299,585.951173,632.696615,0.104832,3840.310600,3,-1,2
4,39490,28,27431.467873,15,832.664792,1.348389,354.568534,0.409204,0.039517,50.123656,...,Semi-Urban,Occasional,9991.977507,478.096258,67.586178,0.409204,1122.755920,2,-1,3

In [7]:
print(df.columns.tolist())

['customer_id', 'age', 'annual_income', 'months_active', 'avg_monthly_spend', 'purchase_frequency', 'avg_order_value', 'discount_usage_rate', 'return_rate', 'browsing_time_minutes', 'support_interactions', 'payment_method', 'region', 'customer_segment', 'estimated_annual_spend', 'purchase_value_index', 'engagement_score', 'discount_dependency', 'customer_value_score', 'Cluster', 'DBSCAN_Cluster', 'Hierarchical_Cluster']

In [10]:
df.head()

,customer_id,age,annual_income,months_active,avg_monthly_spend,purchase_frequency,avg_order_value,discount_usage_rate,return_rate,browsing_time_minutes,...,region,customer_segment,estimated_annual_spend,purchase_value_index,engagement_score,discount_dependency,customer_value_score,Cluster,DBSCAN_Cluster,Hierarchical_Cluster
0,33554,53,100473.211709,63,121.430565,0.817268,66.820403,0.117256,0.023144,77.298393,...,Semi-Urban,Occasional,1457.166781,54.610162,63.173486,0.117256,99.241287,1,-1,1
1,9428,54,54730.644845,67,572.552674,3.176551,137.087449,0.261647,0.429054,92.132565,...,Urban,Occasional,6870.632088,435.465225,292.663757,0.261647,1818.742563,3,-1,2
2,200,44,58268.121079,57,266.593896,2.713168,71.796888,0.284785,0.011854,155.194768,...,Rural,Occasional,3199.126755,194.797008,421.069457,0.284785,723.313990,0,-1,3
3,12448,54,64829.795654,40,691.452358,5.553977,105.501185,0.104832,0.399686,113.917756,...,Rural,High_Value,8297.428299,585.951173,632.696615,0.104832,3840.310600,3,-1,2
4,39490,28,27431.467873,15,832.664792,1.348389,354.568534,0.409204,0.039517,50.123656,...,Semi-Urban,Occasional,9991.977507,478.096258,67.586178,0.409204,1122.755920,2,-1,3

In [9]:
print(df["DBSCAN_Cluster"].value_counts())

DBSCAN_Cluster
-1    50000
Name: count, dtype: int64

In [11]:
print(x_scaled.shape)

(50000, 14)

In [12]:
from sklearn.cluster import DBSCAN

for eps in [0.3, 0.5, 0.7, 1.0, 1.5, 2.0]:
    
    dbscan = DBSCAN(
        eps=eps,
        min_samples=10
    )
    
    labels = dbscan.fit_predict(x_scaled)
    
    print(f"eps={eps}")
    print(pd.Series(labels).value_counts())
    print("-" * 30)

eps=0.3
-1    50000
Name: count, dtype: int64
------------------------------
eps=0.5
-1    50000
Name: count, dtype: int64
------------------------------
eps=0.7
-1    50000
Name: count, dtype: int64
------------------------------
eps=1.0
-1     49749
 0       128
 1        19
 4        15
 9        13
 5        11
 2        10
 6        10
 8        10
 7         9
 11        9
 3         9
 10        8
Name: count, dtype: int64
------------------------------
eps=1.5
-1     19476
 3      9188
 4      4954
 2      4825
 7      2838
 0      2627
 5      2518
 1      1437
 6      1365
 8       714
 17        8
 12        8
 9         8
 15        8
 14        7
 10        7
 11        6
 16        3
 13        3
Name: count, dtype: int64
------------------------------
eps=2.0
 5    11837
 0     7089
 4     6884
 8     4501
 3     4446
-1     4076
 2     4069
 6     2720
 1     2636
 7     1742
Name: count, dtype: int64
------------------------------

In [13]:
from sklearn.cluster import DBSCAN

dbscan = DBSCAN(
    eps=2.0,
    min_samples=10,
    n_jobs=-1
)

df["DBSCAN_Cluster"] = dbscan.fit_predict(x_scaled)

print(df["DBSCAN_Cluster"].value_counts())

DBSCAN_Cluster
 5    11837
 0     7089
 4     6884
 8     4501
 3     4446
-1     4076
 2     4069
 6     2720
 1     2636
 7     1742
Name: count, dtype: int64

In [14]:
from sklearn.metrics import silhouette_score
import pandas as pd

# KMeans
kmeans_score = silhouette_score(
    x_scaled,
    df["Cluster"]
)

# DBSCAN
dbscan_labels = df["DBSCAN_Cluster"]

mask = dbscan_labels != -1

dbscan_score = silhouette_score(
    x_scaled[mask],
    dbscan_labels[mask]
)

# Hierarchical
hierarchical_score = silhouette_score(
    x_scaled,
    df["Hierarchical_Cluster"]
)

comparison = pd.DataFrame({
    "Algorithm": [
        "KMeans",
        "DBSCAN",
        "Hierarchical"
    ],
    
    "Silhouette Score": [
        kmeans_score,
        dbscan_score,
        hierarchical_score
    ]
})

comparison

      Algorithm  Silhouette Score
0        KMeans          0.117741
1        DBSCAN          0.113395
2  Hierarchical          0.098412

In [16]:
df.groupby("Cluster").mean(numeric_only=True)

,customer_id,age,annual_income,months_active,avg_monthly_spend,purchase_frequency,avg_order_value,discount_usage_rate,return_rate,browsing_time_minutes,support_interactions,estimated_annual_spend,purchase_value_index,engagement_score,discount_dependency,customer_value_score,DBSCAN_Cluster,Hierarchical_Cluster
Cluster,,,,,,,,,,,,,,,,,,
0,24977.266455,44.178094,44639.303951,36.549666,284.804221,5.329081,54.672339,0.283412,0.148960,62.016630,1.504370,3417.650657,230.679381,330.056391,0.283412,1613.542571,3.757413,0.079662
1,25028.946826,44.091643,44308.306481,36.189652,303.668255,5.136793,62.222367,0.286236,0.150290,61.480163,1.498841,3644.019064,243.456774,314.470842,0.286236,1622.450916,0.639885,0.932927
2,25256.555151,43.601192,44759.242895,36.209341,645.422756,2.604725,213.707652,0.288004,0.146145,62.058527,1.463362,7745.073077,458.572867,160.306392,0.288004,1954.343224,2.490560,1.493044
3,24861.052882,43.722504,44442.231974,36.809373,309.789908,5.084419,64.248619,0.282154,0.149211,61.379586,1.485481,3717.478894,249.164493,312.972361,0.282154,1640.300814,6.483217,1.833756

In [17]:
df.to_csv('../data/pca_data07.csv')

In [18]:
import pickle

with open("../data/processed_variables.pkl", "wb") as f:
    pickle.dump({
        "df": df,
        "features": features,
        "x_scaled":x_scaled,
        "x_scaled_df":x_scaled_df,
        "scaler":scaler,
        "final_kmeans":final_kmeans,
        "dbscan_results":dbscan_results,
        "comparison":comparison

    }, f)